BEGIN TRANSACTION;

DROP TABLE IF EXISTS bodyshop;

DROP TABLE IF EXISTS app_service;

DROP TABLE IF EXISTS appointment;

DROP TABLE IF EXISTS service;

DROP TABLE IF EXISTS vehicle;

DROP TABLE IF EXISTS client;

COMMIT TRANSACTION;
